// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messages.proto
// Protobuf C++ Version: 5.30.0-dev

#ifndef messages_2eproto_2epb_2eh
#define messages_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5030000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_messages_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_messages_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_messages_2eproto;
namespace ChatMessages {
class UserMessage;
struct UserMessageDefaultTypeInternal;
extern UserMessageDefaultTypeInternal _UserMessage_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull UserMessage_class_data_;
}  // namespace ChatMessages
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace ChatMessages {

// ===================================================================


// -------------------------------------------------------------------

class UserMessage final
    : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:ChatMessages.UserMessage) */ {
 public:
  inline UserMessage() : UserMessage(nullptr) {}
  ~UserMessage() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(UserMessage* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(UserMessage));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR UserMessage(
      ::google::protobuf::internal::ConstantInitialized);

  inline UserMessage(const UserMessage& from) : UserMessage(nullptr, from) {}
  inline UserMessage(UserMessage&& from) noexcept
      : UserMessage(nullptr, std::move(from)) {}
  inline UserMessage& operator=(const UserMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline UserMessage& operator=(UserMessage&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const UserMessage& default_instance() {
    return *internal_default_instance();
  }
  static inline const UserMessage* internal_default_instance() {
    return reinterpret_cast<const UserMessage*>(
        &_UserMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(UserMessage& a, UserMessage& b) { a.Swap(&b); }
  inline void Swap(UserMessage* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(UserMessage* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  UserMessage* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<UserMessage>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const UserMessage& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const UserMessage& from) { UserMessage::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(UserMessage* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "ChatMessages.UserMessage"; }

 protected:
  explicit UserMessage(::google::protobuf::Arena* arena);
  UserMessage(::google::protobuf::Arena* arena, const UserMessage& from);
  UserMessage(::google::protobuf::Arena* arena, UserMessage&& from) noexcept
      : UserMessage(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kMUserNameFieldNumber = 2,
    kMUserIpAddressFieldNumber = 3,
    kMUserSentTimeFieldNumber = 4,
    kMWTFFieldNumber = 5,
    kMUserIdFieldNumber = 1,
  };
  // string m_userName = 2;
  void clear_m_username() ;
  const std::string& m_username() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_m_username(Arg_&& arg, Args_... args);
  std::string* mutable_m_username();
  PROTOBUF_NODISCARD std::string* release_m_username();
  void set_allocated_m_username(std::string* value);

  private:
  const std::string& _internal_m_username() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_m_username(
      const std::string& value);
  std::string* _internal_mutable_m_username();

  public:
  // string m_userIpAddress = 3;
  void clear_m_useripaddress() ;
  const std::string& m_useripaddress() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_m_useripaddress(Arg_&& arg, Args_... args);
  std::string* mutable_m_useripaddress();
  PROTOBUF_NODISCARD std::string* release_m_useripaddress();
  void set_allocated_m_useripaddress(std::string* value);

  private:
  const std::string& _internal_m_useripaddress() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_m_useripaddress(
      const std::string& value);
  std::string* _internal_mutable_m_useripaddress();

  public:
  // string m_userSentTime = 4;
  void clear_m_usersenttime() ;
  const std::string& m_usersenttime() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_m_usersenttime(Arg_&& arg, Args_... args);
  std::string* mutable_m_usersenttime();
  PROTOBUF_NODISCARD std::string* release_m_usersenttime();
  void set_allocated_m_usersenttime(std::string* value);

  private:
  const std::string& _internal_m_usersenttime() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_m_usersenttime(
      const std::string& value);
  std::string* _internal_mutable_m_usersenttime();

  public:
  // string m_WTF = 5;
  void clear_m_wtf() ;
  const std::string& m_wtf() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_m_wtf(Arg_&& arg, Args_... args);
  std::string* mutable_m_wtf();
  PROTOBUF_NODISCARD std::string* release_m_wtf();
  void set_allocated_m_wtf(std::string* value);

  private:
  const std::string& _internal_m_wtf() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_m_wtf(
      const std::string& value);
  std::string* _internal_mutable_m_wtf();

  public:
  // uint64 m_userId = 1;
  void clear_m_userid() ;
  ::uint64_t m_userid() const;
  void set_m_userid(::uint64_t value);

  private:
  ::uint64_t _internal_m_userid() const;
  void _internal_set_m_userid(::uint64_t value);

  public:
  // @@protoc_insertion_point(class_scope:ChatMessages.UserMessage)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 5, 0,
      77, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const UserMessage& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr m_username_;
    ::google::protobuf::internal::ArenaStringPtr m_useripaddress_;
    ::google::protobuf::internal::ArenaStringPtr m_usersenttime_;
    ::google::protobuf::internal::ArenaStringPtr m_wtf_;
    ::uint64_t m_userid_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_messages_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull UserMessage_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// UserMessage

// uint64 m_userId = 1;
inline void UserMessage::clear_m_userid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.m_userid_ = ::uint64_t{0u};
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline ::uint64_t UserMessage::m_userid() const {
  // @@protoc_insertion_point(field_get:ChatMessages.UserMessage.m_userId)
  return _internal_m_userid();
}
inline void UserMessage::set_m_userid(::uint64_t value) {
  _internal_set_m_userid(value);
  _impl_._has_bits_[0] |= 0x00000010u;
  // @@protoc_insertion_point(field_set:ChatMessages.UserMessage.m_userId)
}
inline ::uint64_t UserMessage::_internal_m_userid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.m_userid_;
}
inline void UserMessage::_internal_set_m_userid(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.m_userid_ = value;
}

// string m_userName = 2;
inline void UserMessage::clear_m_username() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.m_username_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& UserMessage::m_username() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ChatMessages.UserMessage.m_userName)
  return _internal_m_username();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void UserMessage::set_m_username(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.m_username_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:ChatMessages.UserMessage.m_userName)
}
inline std::string* UserMessage::mutable_m_username() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_m_username();
  // @@protoc_insertion_point(field_mutable:ChatMessages.UserMessage.m_userName)
  return _s;
}
inline const std::string& UserMessage::_internal_m_username() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.m_username_.Get();
}
inline void UserMessage::_internal_set_m_username(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.m_username_.Set(value, GetArena());
}
inline std::string* UserMessage::_internal_mutable_m_username() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.m_username_.Mutable( GetArena());
}
inline std::string* UserMessage::release_m_username() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:ChatMessages.UserMessage.m_userName)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.m_username_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.m_username_.Set("", GetArena());
  }
  return released;
}
inline void UserMessage::set_allocated_m_username(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.m_username_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.m_username_.IsDefault()) {
    _impl_.m_username_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:ChatMessages.UserMessage.m_userName)
}

// string m_userIpAddress = 3;
inline void UserMessage::clear_m_useripaddress() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.m_useripaddress_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const std::string& UserMessage::m_useripaddress() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ChatMessages.UserMessage.m_userIpAddress)
  return _internal_m_useripaddress();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void UserMessage::set_m_useripaddress(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.m_useripaddress_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:ChatMessages.UserMessage.m_userIpAddress)
}
inline std::string* UserMessage::mutable_m_useripaddress() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_m_useripaddress();
  // @@protoc_insertion_point(field_mutable:ChatMessages.UserMessage.m_userIpAddress)
  return _s;
}
inline const std::string& UserMessage::_internal_m_useripaddress() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.m_useripaddress_.Get();
}
inline void UserMessage::_internal_set_m_useripaddress(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.m_useripaddress_.Set(value, GetArena());
}
inline std::string* UserMessage::_internal_mutable_m_useripaddress() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.m_useripaddress_.Mutable( GetArena());
}
inline std::string* UserMessage::release_m_useripaddress() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:ChatMessages.UserMessage.m_userIpAddress)
  if ((_impl_._has_bits_[0] & 0x00000002u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* released = _impl_.m_useripaddress_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.m_useripaddress_.Set("", GetArena());
  }
  return released;
}
inline void UserMessage::set_allocated_m_useripaddress(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.m_useripaddress_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.m_useripaddress_.IsDefault()) {
    _impl_.m_useripaddress_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:ChatMessages.UserMessage.m_userIpAddress)
}

// string m_userSentTime = 4;
inline void UserMessage::clear_m_usersenttime() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.m_usersenttime_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline const std::string& UserMessage::m_usersenttime() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ChatMessages.UserMessage.m_userSentTime)
  return _internal_m_usersenttime();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void UserMessage::set_m_usersenttime(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.m_usersenttime_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:ChatMessages.UserMessage.m_userSentTime)
}
inline std::string* UserMessage::mutable_m_usersenttime() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_m_usersenttime();
  // @@protoc_insertion_point(field_mutable:ChatMessages.UserMessage.m_userSentTime)
  return _s;
}
inline const std::string& UserMessage::_internal_m_usersenttime() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.m_usersenttime_.Get();
}
inline void UserMessage::_internal_set_m_usersenttime(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.m_usersenttime_.Set(value, GetArena());
}
inline std::string* UserMessage::_internal_mutable_m_usersenttime() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004u;
  return _impl_.m_usersenttime_.Mutable( GetArena());
}
inline std::string* UserMessage::release_m_usersenttime() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:ChatMessages.UserMessage.m_userSentTime)
  if ((_impl_._has_bits_[0] & 0x00000004u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000004u;
  auto* released = _impl_.m_usersenttime_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.m_usersenttime_.Set("", GetArena());
  }
  return released;
}
inline void UserMessage::set_allocated_m_usersenttime(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  _impl_.m_usersenttime_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.m_usersenttime_.IsDefault()) {
    _impl_.m_usersenttime_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:ChatMessages.UserMessage.m_userSentTime)
}

// string m_WTF = 5;
inline void UserMessage::clear_m_wtf() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.m_wtf_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline const std::string& UserMessage::m_wtf() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ChatMessages.UserMessage.m_WTF)
  return _internal_m_wtf();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void UserMessage::set_m_wtf(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000008u;
  _impl_.m_wtf_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:ChatMessages.UserMessage.m_WTF)
}
inline std::string* UserMessage::mutable_m_wtf() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_m_wtf();
  // @@protoc_insertion_point(field_mutable:ChatMessages.UserMessage.m_WTF)
  return _s;
}
inline const std::string& UserMessage::_internal_m_wtf() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.m_wtf_.Get();
}
inline void UserMessage::_internal_set_m_wtf(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000008u;
  _impl_.m_wtf_.Set(value, GetArena());
}
inline std::string* UserMessage::_internal_mutable_m_wtf() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000008u;
  return _impl_.m_wtf_.Mutable( GetArena());
}
inline std::string* UserMessage::release_m_wtf() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:ChatMessages.UserMessage.m_WTF)
  if ((_impl_._has_bits_[0] & 0x00000008u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000008u;
  auto* released = _impl_.m_wtf_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.m_wtf_.Set("", GetArena());
  }
  return released;
}
inline void UserMessage::set_allocated_m_wtf(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000008u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000008u;
  }
  _impl_.m_wtf_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.m_wtf_.IsDefault()) {
    _impl_.m_wtf_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:ChatMessages.UserMessage.m_WTF)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace ChatMessages


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // messages_2eproto_2epb_2eh
